In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
scalar = tf.constant(7)
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector.ndim

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
matrix= tf.constant([[10,7],[7,10]])
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[1,2,3],[6,7,8]],
                      [[3,3,3],[4,4,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [6, 7, 8]],

       [[3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [ ]:
chanagable_tensor = tf.Variable([10,7])
chanagable_tensor[0].assign(7)
chanagable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(4)
random_1 = random_1.normal(shape=(3,3,3,3))
random_1

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[ 1.0019137 ,  0.6735137 ,  0.06987712],
         [-1.4077919 ,  1.0278524 ,  0.27974114],
         [-0.01347923,  1.845181  ,  0.97061104]],

        [[-1.0242516 , -0.6544423 , -0.29738766],
         [-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707]],

        [[-0.06378496,  0.92800784, -0.6039789 ],
         [-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002]]],


       [[[ 1.5165398 ,  0.27305737, -0.29925638],
         [-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967]],

        [[ 0.37944323, -0.6664026 ,  0.6054596 ],
         [ 0.19181173,  0.8045827 ,  0.4769051 ],
         [-0.7812124 , -0.996891  ,  0.33149973]],

        [[-0.5445254 ,  1.5222508 ,  0.59303206],
         [-0.63509274,  0.3703566 , -1.0939722 ],
         [-0.4601445 ,  1.5420506 , -0.16822556]]],


       [[[-0.4390865 , -0.4129

In [ ]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# ***Day 2***


In [ ]:
tf.ones([2,10])
tf.zeros([3,3,2])

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
A = tf.constant(numpy_A,shape=(2,3,4))
A


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [47]:
tensor_A[:,:,2,2]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]], dtype=int32)>

In [50]:
tensor_A = tf.constant(list(range(1,9)),shape=(2,2,2))
tf.expand_dims(tensor_A,axis=0)

<tf.Tensor: shape=(1, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]], dtype=int32)>